name: numerology
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.1+20

environment:
  sdk: '>=3.7.2 <4.0.0' # SDK 버전 수정

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^2.1.0
  sweph: ^2.10.3
  another_flushbar: ^1.2.2
  animated_theme_switcher: ^2.0.10
  provider: ^6.1.2
  google_fonts: ^6.1.0
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.0.0
  table_calendar: ^3.1.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.0 
  url_launcher: ^6.0.0 
  google_mobile_ads: ^6.0.0
  upgrader: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # 여기에 추가

flutter_launcher_icons:
  android: true
  image_path: "assets/512_512.png" # 이미지의 실제

flutter:
  uses-material-design: true
  generate: true